//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WindowsFormsApp3.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="n_cst_guardserviceSoap", Namespace="http://tempurl.org")]
    public partial class n_cst_guardservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback uf_check_carnumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback uf_receive_carnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback uf_get_teetimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback uf_get_golferlistOperationCompleted;
        
        private System.Threading.SendOrPostCallback uf_get_msgtxtOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public n_cst_guardservice() {
            this.Url = global::WindowsFormsApp3.Properties.Settings.Default.WindowsFormsApp3_WebReference_n_cst_guardservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event uf_check_carnumberCompletedEventHandler uf_check_carnumberCompleted;
        
        /// <remarks/>
        public event uf_receive_carnoCompletedEventHandler uf_receive_carnoCompleted;
        
        /// <remarks/>
        public event uf_get_teetimeCompletedEventHandler uf_get_teetimeCompleted;
        
        /// <remarks/>
        public event uf_get_golferlistCompletedEventHandler uf_get_golferlistCompleted;
        
        /// <remarks/>
        public event uf_get_msgtxtCompletedEventHandler uf_get_msgtxtCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempurl.org/uf_check_carnumber", RequestNamespace="http://tempurl.org", ResponseNamespace="http://tempurl.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public short uf_check_carnumber(string as_number) {
            object[] results = this.Invoke("uf_check_carnumber", new object[] {
                        as_number});
            return ((short)(results[0]));
        }
        
        /// <remarks/>
        public void uf_check_carnumberAsync(string as_number) {
            this.uf_check_carnumberAsync(as_number, null);
        }
        
        /// <remarks/>
        public void uf_check_carnumberAsync(string as_number, object userState) {
            if ((this.uf_check_carnumberOperationCompleted == null)) {
                this.uf_check_carnumberOperationCompleted = new System.Threading.SendOrPostCallback(this.Onuf_check_carnumberOperationCompleted);
            }
            this.InvokeAsync("uf_check_carnumber", new object[] {
                        as_number}, this.uf_check_carnumberOperationCompleted, userState);
        }
        
        private void Onuf_check_carnumberOperationCompleted(object arg) {
            if ((this.uf_check_carnumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uf_check_carnumberCompleted(this, new uf_check_carnumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempurl.org/uf_receive_carno", RequestNamespace="http://tempurl.org", ResponseNamespace="http://tempurl.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string uf_receive_carno(string as_key, string as_name, string as_number) {
            object[] results = this.Invoke("uf_receive_carno", new object[] {
                        as_key,
                        as_name,
                        as_number});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uf_receive_carnoAsync(string as_key, string as_name, string as_number) {
            this.uf_receive_carnoAsync(as_key, as_name, as_number, null);
        }
        
        /// <remarks/>
        public void uf_receive_carnoAsync(string as_key, string as_name, string as_number, object userState) {
            if ((this.uf_receive_carnoOperationCompleted == null)) {
                this.uf_receive_carnoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onuf_receive_carnoOperationCompleted);
            }
            this.InvokeAsync("uf_receive_carno", new object[] {
                        as_key,
                        as_name,
                        as_number}, this.uf_receive_carnoOperationCompleted, userState);
        }
        
        private void Onuf_receive_carnoOperationCompleted(object arg) {
            if ((this.uf_receive_carnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uf_receive_carnoCompleted(this, new uf_receive_carnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempurl.org/uf_get_teetime", RequestNamespace="http://tempurl.org", ResponseNamespace="http://tempurl.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string uf_get_teetime(System.DateTime ad_date) {
            object[] results = this.Invoke("uf_get_teetime", new object[] {
                        ad_date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uf_get_teetimeAsync(System.DateTime ad_date) {
            this.uf_get_teetimeAsync(ad_date, null);
        }
        
        /// <remarks/>
        public void uf_get_teetimeAsync(System.DateTime ad_date, object userState) {
            if ((this.uf_get_teetimeOperationCompleted == null)) {
                this.uf_get_teetimeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onuf_get_teetimeOperationCompleted);
            }
            this.InvokeAsync("uf_get_teetime", new object[] {
                        ad_date}, this.uf_get_teetimeOperationCompleted, userState);
        }
        
        private void Onuf_get_teetimeOperationCompleted(object arg) {
            if ((this.uf_get_teetimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uf_get_teetimeCompleted(this, new uf_get_teetimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempurl.org/uf_get_golferlist", RequestNamespace="http://tempurl.org", ResponseNamespace="http://tempurl.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string uf_get_golferlist(System.DateTime ad_date) {
            object[] results = this.Invoke("uf_get_golferlist", new object[] {
                        ad_date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uf_get_golferlistAsync(System.DateTime ad_date) {
            this.uf_get_golferlistAsync(ad_date, null);
        }
        
        /// <remarks/>
        public void uf_get_golferlistAsync(System.DateTime ad_date, object userState) {
            if ((this.uf_get_golferlistOperationCompleted == null)) {
                this.uf_get_golferlistOperationCompleted = new System.Threading.SendOrPostCallback(this.Onuf_get_golferlistOperationCompleted);
            }
            this.InvokeAsync("uf_get_golferlist", new object[] {
                        ad_date}, this.uf_get_golferlistOperationCompleted, userState);
        }
        
        private void Onuf_get_golferlistOperationCompleted(object arg) {
            if ((this.uf_get_golferlistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uf_get_golferlistCompleted(this, new uf_get_golferlistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempurl.org/uf_get_msgtxt", RequestNamespace="http://tempurl.org", ResponseNamespace="http://tempurl.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string uf_get_msgtxt(int al_id) {
            object[] results = this.Invoke("uf_get_msgtxt", new object[] {
                        al_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uf_get_msgtxtAsync(int al_id) {
            this.uf_get_msgtxtAsync(al_id, null);
        }
        
        /// <remarks/>
        public void uf_get_msgtxtAsync(int al_id, object userState) {
            if ((this.uf_get_msgtxtOperationCompleted == null)) {
                this.uf_get_msgtxtOperationCompleted = new System.Threading.SendOrPostCallback(this.Onuf_get_msgtxtOperationCompleted);
            }
            this.InvokeAsync("uf_get_msgtxt", new object[] {
                        al_id}, this.uf_get_msgtxtOperationCompleted, userState);
        }
        
        private void Onuf_get_msgtxtOperationCompleted(object arg) {
            if ((this.uf_get_msgtxtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uf_get_msgtxtCompleted(this, new uf_get_msgtxtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void uf_check_carnumberCompletedEventHandler(object sender, uf_check_carnumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uf_check_carnumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uf_check_carnumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public short Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void uf_receive_carnoCompletedEventHandler(object sender, uf_receive_carnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uf_receive_carnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uf_receive_carnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void uf_get_teetimeCompletedEventHandler(object sender, uf_get_teetimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uf_get_teetimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uf_get_teetimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void uf_get_golferlistCompletedEventHandler(object sender, uf_get_golferlistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uf_get_golferlistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uf_get_golferlistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void uf_get_msgtxtCompletedEventHandler(object sender, uf_get_msgtxtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uf_get_msgtxtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uf_get_msgtxtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591